import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto}from'node:crypto';
import {loadLamaArtifact}from'../src/ai/asset-cache.js';import{createLamaEngine}from'../src/ai/lama-runtime.js';
const bytes=new Uint8Array([1,2,3,4]),sha=Buffer.from(await webcrypto.subtle.digest('SHA-256',bytes)).toString('hex');const descriptor={id:'test',url:'https://example.invalid/pinned',size:4,sha256:sha};
const response=value=>({ok:true,headers:new Headers(),body:new ReadableStream({start(c){c.enqueue(new Uint8Array(value));c.close();}})});
test('verified cache prevents any fetch; corrupt cache is rejected in offline mode',async()=>{let fetched=0;let value=await loadLamaArtifact(descriptor,{cryptoImpl:webcrypto,cachedOnly:true,cache:{get:async()=>bytes.buffer},fetchImpl:()=>{fetched++;}});assert.equal(value,bytes.buffer);assert.equal(fetched,0);await assert.rejects(loadLamaArtifact(descriptor,{cryptoImpl:webcrypto,cachedOnly:true,cache:{get:async()=>new Uint8Array([4,3,2,1]).buffer}}));});
test('artifact requests omit credentials/referrer and contain no photo; quota failure does not fail model',async()=>{let options,stored;let value=await loadLamaArtifact(descriptor,{cryptoImpl:webcrypto,cache:{get:async()=>null,put:async()=>{throw new Error('quota');}},fetchImpl:async(url,opt)=>{assert.equal(url,descriptor.url);options=opt;return response(bytes);},onCacheResult:v=>stored=v});assert.equal(value.byteLength,4);assert.equal(options.method,'GET');assert.equal(options.credentials,'omit');assert.equal(options.referrerPolicy,'no-referrer');assert.equal(options.body,undefined);assert.equal(stored,false);});
test('oversize and integrity failures never enter cache',async()=>{for(const value of [[1,2,3,4,5],[4,3,2,1]]){let puts=0;await assert.rejects(loadLamaArtifact(descriptor,{cryptoImpl:webcrypto,cache:{get:async()=>null,put:async()=>puts++},fetchImpl:async()=>response(value)}));assert.equal(puts,0);}});
test('abort prevents network and worker termination rejects late result',async()=>{const a=new AbortController();a.abort();await assert.rejects(loadLamaArtifact(descriptor,{signal:a.signal,cryptoImpl:webcrypto,fetchImpl:()=>assert.fail('no fetch')}));let terminated=0,w={terminate(){terminated++;},postMessage(){}};let engine=createLamaEngine({artifactList:[descriptor,descriptor,descriptor,descriptor],load:async(_d,opt)=>{opt.onCacheResult(true);return bytes.buffer.slice(0);},workerFactory:()=>w});await engine.prepare();let b=new AbortController(),p=engine.run(new Float32Array(4*512*512),{signal:b.signal});b.abort();await assert.rejects(p,/отменено/);assert.ok(terminated>0);w.onmessage({data:{type:'result',output:new Float32Array(3)}});assert.equal(engine.isReady(),true);});

test('canceled worker ignores late progress and cannot seed a future remaining-time estimate',async()=>{let workers=[],events=[];let engine=createLamaEngine({artifactList:[descriptor,descriptor,descriptor,descriptor],load:async()=>bytes.buffer.slice(0),workerFactory:()=>{let w={terminate(){},postMessage(){}};workers.push(w);return w;}});await engine.prepare();let controller=new AbortController();let first=engine.run(new Float32Array(4*512*512),{signal:controller.signal,onProgress:e=>events.push(e)});workers[0].onmessage({data:{type:'progress',stage:'inference',message:'working'}});controller.abort();await assert.rejects(first);workers[0].onmessage({data:{type:'progress',stage:'inference',message:'late'}});workers[0].onmessage({data:{type:'result',output:new Float32Array(3)}});assert.equal(events.length,1);let second=engine.run(new Float32Array(4*512*512),{onProgress:e=>events.push(e)});workers[1].onmessage({data:{type:'progress',stage:'inference',message:'working'}});assert.equal(events[1].estimatedSeconds,undefined);workers[1].onmessage({data:{type:'result',output:new Float32Array(3)}});await second;});
