import test from 'node:test';
import assert from 'node:assert/strict';
import { prepareLamaInput, mergeLamaOutput } from '../src/ai/lama-preprocess.js';
import { createObjectRemovalCommandController } from '../src/painting/object-removal-command-controller.js';
const fixture=()=>{let w=20,h=12,rgba=new Uint8ClampedArray(w*h*4),mask=new Uint8Array(w*h);for(let i=0;i<w*h;i++){rgba.set([40,80,120,i%256],i*4);}mask[6*w+10]=1;return {width:w,height:h,data:rgba,mask};};
test('model input has correct masked RGB and binary fourth channel; aspect ratio is preserved',()=>{let f=fixture(),p=prepareLamaInput(f);assert.equal(p.input.length,4*512*512);assert.equal(p.crop.width/p.crop.height,20/12);let n=512*512,count=0;for(let i=0;i<n;i++){assert.ok(p.input[3*n+i]===0||p.input[3*n+i]===1);if(p.input[3*n+i]){count++;assert.equal(p.input[i],0);}}assert.ok(count>0);});
test('merge replaces only painted RGB, preserves all alpha and rejects malformed/nonfinite output',()=>{let f=fixture(),p=prepareLamaInput(f),o=new Float32Array(3*512*512).fill(.5),r=mergeLamaOutput(f,p,o);for(let i=0;i<f.mask.length;i++){assert.equal(r[i*4+3],f.data[i*4+3]);assert.equal(r[i*4],f.mask[i]?128:40);}assert.throws(()=>mergeLamaOutput(f,p,new Float32Array(3)));o[123]=NaN;assert.throws(()=>mergeLamaOutput(f,p,o));});
test('empty/full masks and oversized sources are rejected before tensor allocation',()=>{let f=fixture();f.mask.fill(0);assert.throws(()=>prepareLamaInput(f));f.mask.fill(1);assert.throws(()=>prepareLamaInput(f));assert.throws(()=>prepareLamaInput({...f,width:9000,height:9000}));});
function harness(){let layer={width:20,height:12},doc={layers:[layer]},current=true,pending=false,commits=0,writes=0,clears=0,persisted=0,release;
const f=fixture();const c=createObjectRemovalCommandController({state:{getDocument:()=>doc,beginPersist:()=>pending?false:(pending=true),endPersist:()=>{pending=false;}},rasterEdit:{ensureRasterBuffer:async()=>({canvas:{width:20,height:12},ctx:{getImageData:()=>({data:f.data.slice()}),putImageData:()=>{writes++;}}}),persistPaintLayer:async(_d,_l,opt)=>{await Promise.resolve();if(!opt.isContinuationCurrent())return false;persisted++;return true;},clearBrushBuffer:()=>{clears++;}},engine:{run:async()=>new Promise(r=>{release=r;})},ui:{commit:()=>{commits++;},setStatus(){},render(){}}});return {c,layer,doc,f,args:()=>({ownerDocument:doc,ownerLayer:layer,mask:{width:20,height:12,data:f.mask},isCurrent:()=>current,signal:new AbortController().signal}),stale(){current=false;},resolve(o=new Float32Array(3*512*512).fill(.5)){release(o);},counts:()=>({pending,commits,writes,clears,persisted})};}
test('one successful removal makes one commit and releases shared persistence',async()=>{let h=harness(),r=h.c.remove(h.args());await new Promise(r=>setImmediate(r));h.resolve();assert.equal(await r,true);assert.deepEqual(h.counts(),{pending:false,commits:1,writes:1,clears:1,persisted:1});});
test('stale target after inference never writes pixels or history',async()=>{let h=harness(),r=h.c.remove(h.args());await new Promise(r=>setImmediate(r));h.stale();h.resolve();assert.equal(await r,false);assert.equal(h.counts().writes,0);assert.equal(h.counts().commits,0);assert.equal(h.counts().pending,false);});
test('native high depth is rejected without loading model or mutating source',async()=>{let h=harness();h.layer.highDepthSource={bitDepth:16};assert.equal(await h.c.remove(h.args()),false);assert.equal(h.counts().writes,0);assert.equal(h.counts().pending,false);});
test('cancel and invalid output retain original pixels/history',async()=>{for(const mode of ['cancel','nan']){let h=harness(),a=h.args(),r=h.c.remove(a);await new Promise(r=>setImmediate(r));if(mode==='cancel')h.stale();let o=new Float32Array(3*512*512);if(mode==='nan')o[4]=NaN;h.resolve(o);assert.equal(await r,false);assert.equal(h.counts().writes,0);assert.equal(h.counts().commits,0);}});

test('extreme aspect ratios keep at least one model pixel and a nonempty erase mask',()=>{for(const [width,height]of [[3000,1],[1,3000]]){const data=new Uint8ClampedArray(width*height*4),mask=new Uint8Array(width*height);mask[100]=mask[2800]=1;let p=prepareLamaInput({width,height,data,mask});assert.ok(p.tw>=1&&p.th>=1);assert.ok(p.input.slice(3*512*512).some(v=>v===1));}});
test('actual aborted command never publishes an inference result',async()=>{let h=harness(),abort=new AbortController(),args={...h.args(),signal:abort.signal},p=h.c.remove(args);await new Promise(r=>setImmediate(r));abort.abort();h.resolve();assert.equal(await p,false);assert.equal(h.counts().writes,0);assert.equal(h.counts().commits,0);});
