import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createPixelBuffer, inpaintTiledPixelBufferSourceFromIndices, serializeTiledPixelBufferSource } from '../src/core/pixel-buffer.js';
import { encodePsd, encodePsb } from '../src/formats/psd.js';
import { inspectExternalHighDepthHeader } from '../tools/audit-external-high-depth-corpus.mjs';
import {
  profileHighDepthBytes, assertHighDepthWorkerParity,
} from '../tools/profile-external-high-depth-psd-psb.mjs';

const cli = fileURLToPath(new URL('../tools/profile-external-high-depth-psd-psb.mjs', import.meta.url));

// These files are generated by ZeTer's own PSD writer, not by Photoshop.
// They exercise only the new harness and must never be counted as external
// compatibility/provenance evidence.
function syntheticFixture(id) {
  const depth = id === 'psd16' ? 16 : 32;
  const ArrayType = depth === 16 ? Uint16Array : Float32Array;
  const background = depth === 16 ? [12000, 20000, 30000, 65535] : [0.25, -0.5, 2.5, 1];
  const defect = depth === 16 ? [61000, 50000, 40000, 65535] : [9, 5, 7, 1];
  const width = 8, height = 8, channels = 4;
  const samples = new ArrayType(width * height * channels);
  for (let index = 0; index < width * height; index += 1) {
    samples.set(index === 4 * width + 4 ? defect : background, index * channels);
  }
  const pixelBuffer = createPixelBuffer({
    width, height, model:'rgb', channels, bitsPerChannel:depth,
    colorSpace:depth === 16 ? 'srgb' : 'linear-rgb-unmanaged', data:samples,
  });
  const encode = id === 'psd16' ? encodePsd : encodePsb;
  const bytes = encode({
    width, height, bitsPerChannel:depth, compositePixelBuffer:pixelBuffer,
    layers:[{
      name:'Synthetic high-depth test', x:0, y:0, width, height, pixelBuffer,
      opacity:1, blendMode:'source-over', visible:true,
    }],
  });
  const header = inspectExternalHighDepthHeader(bytes);
  return {
    bytes, pixelBuffer, expected:{
      id, file:id + (depth === 16 ? '.psd' : '.psb'),
      bytes:bytes.byteLength,
      sha256:createHash('sha256').update(bytes).digest('hex'), ...header,
    },
  };
}

test('Stage 002: synthetic PSD16/PSB32 decode, native tiling and actual Worker pass without quantization', async () => {
  for (const id of ['psd16', 'psb32']) {
    const { bytes, expected } = syntheticFixture(id);
    const report = await profileHighDepthBytes(bytes, expected, { tileSize:4 });
    assert.equal(report.fixture, id);
    assert.equal(report.bitsPerChannel, id === 'psd16' ? 16 : 32);
    assert.equal(report.pixelOrigin, 'layer');
    assert.equal(report.tileCount, 4);
    assert.equal(report.filled, 1);
    assert.equal(report.changedTiles, 1);
    assert.equal(report.workersCreated, 1);
    assert.equal(report.selectionSamples, 64);
    assert.equal(report.workerParity, 'exact');
    for (const stage of ['before', 'afterDecode', 'afterTiles', 'afterWorker', 'afterOracle']) {
      assert.ok(Number.isFinite(report.memory[stage].rssMiB));
    }
    for (const stage of ['decodeMs', 'tilesMs', 'workerMs', 'oracleMs']) {
      assert.ok(Number.isFinite(report[stage]) && report[stage] >= 0);
    }
  }
});


test('Stage 002: oracle gate rejects altered Worker counters, metadata and changed tile bytes', () => {
  const { pixelBuffer } = syntheticFixture('psd16');
  const source = serializeTiledPixelBufferSource(pixelBuffer, { tileSize:4 });
  const reference = inpaintTiledPixelBufferSourceFromIndices(source, {
    selectedIndices:Uint32Array.of(4 * source.width + 4),
  });
  assert.doesNotThrow(() => assertHighDepthWorkerParity(reference, reference));
  const reject = candidate => assert.throws(
    () => assertHighDepthWorkerParity(candidate, reference), /differs from native frozen-index oracle/,
  );
  reject({ ...reference, filled:reference.filled + 1 });
  reject({ ...reference, loadedTiles:reference.loadedTiles + 1 });
  reject({ ...reference, source:{ ...reference.source, bitsPerChannel:8 } });
  const alteredTiles = reference.source.tiles.map((tile, index) =>
    index === 3 ? { ...tile, dataUrl:tile.dataUrl + 'corruption' } : tile);
  reject({ ...reference, source:{ ...reference.source, tiles:alteredTiles } });
  assert.deepEqual(source.tiles.map(tile => tile.dataUrl),
    serializeTiledPixelBufferSource(pixelBuffer, { tileSize:4 }).tiles.map(tile => tile.dataUrl),
    'oracle and failed parity checks do not mutate the pinned source');
});

test('Stage 002: a post-audit fixture hash or metadata mismatch fails before decode/Worker', async () => {
  const { bytes, expected } = syntheticFixture('psd16');
  await assert.rejects(profileHighDepthBytes(bytes, { ...expected, sha256:'0'.repeat(64) }),
    /differs from audited fixture/);
  await assert.rejects(profileHighDepthBytes(bytes, { ...expected, bitsPerChannel:32 }),
    /differs from audited fixture/);
});

test('Stage 002: manifest CLI validates both synthetic files and reports explicit provenance/browser limitations', async t => {
  const directory = await mkdtemp(join(tmpdir(), 'zpe-synthetic-high-depth-'));
  t.after(() => rm(directory, { recursive:true, force:true }));
  const fixtures = [];
  for (const id of ['psd16', 'psb32']) {
    const { bytes, expected } = syntheticFixture(id);
    await writeFile(join(directory, expected.file), bytes);
    // The audit schema requires this declared value, but it is demonstrably
    // UNTRUSTED: these test fixtures are ZeTer-written, not Adobe-written.
    fixtures.push({
      id, file:expected.file, size:expected.bytes, sha256:expected.sha256,
      width:expected.width, height:expected.height,
      channels:expected.channels, colorMode:expected.colorMode,
      sourceApplication:'Adobe Photoshop',
      sourceUrl:'https://example.org/UNTRUSTED-SYNTHETIC/' + expected.file,
      license:'Synthetic test only — not an independent Photoshop fixture',
      licenseUrl:'https://example.org/UNTRUSTED-SYNTHETIC-LICENSE',
      provenanceNotes:'This is deliberately synthetic test data from the ZeTer writer; the manifest declaration is not external proof.',
    });
  }
  const manifestPath = join(directory, 'manifest.json');
  await writeFile(manifestPath, JSON.stringify({
    schema:'zpe-external-high-depth-psd-psb-v1', fixtures,
  }));
  const child = spawnSync(process.execPath, [cli, '--manifest', manifestPath], {
    encoding:'utf8', maxBuffer:1024 * 1024,
  });
  assert.equal(child.status, 0, child.stderr);
  const report = JSON.parse(child.stdout);
  assert.equal(report.kind, 'zpe-external-high-depth-psd-psb-native-worker-v1');
  assert.equal(report.passed, true);
  assert.deepEqual(report.fixtures.map(fixture => fixture.bitsPerChannel), [16, 32]);
  assert.deepEqual(report.fixtures.map(fixture => fixture.workerParity), ['exact', 'exact']);
  assert.match(report.limitations, /not peak RSS/);
  assert.match(report.limitations, /No Chromium file:\/\//);
});

test('Stage 002: CLI rejects invocation without an explicit audited manifest', () => {
  const child = spawnSync(process.execPath, [cli], { encoding:'utf8' });
  assert.notEqual(child.status, 0);
  assert.match(child.stderr, /Usage:.*--manifest/);
});
